## EDA:exploratory data **analysis**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
plt.rcParams['figure.figsize']=(10,5)   #runtime configuration given for size of graph not given means graph will be given in default
plt.rcParams['figure.dpi']=300
%matplotlib inline   #donot need plot.show()
import warnings
warnings.filterwarnings("ignore")

In [8]:
df=pd.read_csv("/content/data_clean1.csv")

In [9]:
df

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [10]:
df.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [12]:
df.tail(10)

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
148   30.0    193.0   6.9     9   26  2010    70       C
149    NaN    145.0  13.2     9   27  2010    77      PS
150   14.0    191.0  14.3     9   28  2010    75       S
151   18.0    131.0   8.0     9   29  2010    76      PS
152   20.0    223.0  11.5     9   30  2010    68       S
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

In [13]:
df.describe()  #month also a numeric but it is not printed here

            Ozone     Solar.R        Wind         Day    Year        Temp
count  120.000000  151.000000  158.000000  158.000000   158.0  158.000000
mean    41.583333  185.403974    9.957595   16.006329  2010.0   77.727848
std     32.620709   88.723103    3.511261    8.997166     0.0    9.377877
min      1.000000    7.000000    1.700000    1.000000  2010.0   56.000000
25%     18.000000  119.000000    7.400000    8.000000  2010.0   72.000000
50%     30.500000  197.000000    9.700000   16.000000  2010.0   78.500000
75%     61.500000  257.000000   11.875000   24.000000  2010.0   84.000000
max    168.000000  334.000000   20.700000   31.000000  2010.0   97.000000

In [14]:
df.describe(include=object)

       Month Weather
count    158     155
unique     6       3
top        9       S
freq      34      59

In [15]:
df.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [17]:
df.info()   #find all missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    120 non-null    float64
 1   Solar.R  151 non-null    float64
 2   Wind     158 non-null    float64
 3   Month    158 non-null    object
 4   Day      158 non-null    int64
 5   Year     158 non-null    int64
 6   Temp     158 non-null    int64
 7   Weather  155 non-null    object
dtypes: float64(3), int64(3), object(2)
memory usage: 10.0+ KB

# **DATA TYPE CONVERSION**

In [19]:
df['Month']

0      5
1      5
2      5
3      5
4      5
      ..
153    5
154    9
155    9
156    9
157    9
Name: Month, Length: 158, dtype: object

In [29]:
df['Month'].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [23]:
df['Month'].value_counts()

Month
9      34
5      31
7      31
8      31
6      30
May     1
Name: count, dtype: int64

In [24]:
df['Month'].replace("may","5",inplace=True)  #make permanent changge in memory

In [25]:
df

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [27]:
df['Month'].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [31]:
df['Month'].astype(int)  #made temporal change in memory

ValueError: invalid literal for int() with base 10: 'May'

In [34]:
df.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [36]:
df['Month']=df['Month'].astype(int)

ValueError: invalid literal for int() with base 10: 'May'

Duplicate

In [37]:
df

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [38]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
153    False
154    False
155    False
156     True
157    False
Length: 158, dtype: bool

In [39]:
df.duplicated().sum()

1